version: '3.4'
services:
  chaosengine:
    image: thalesgroup/chaos-engine:stable
    build:
      context: .
      target: develop
    ports:
      - "8080:8080"
    environment:
      VAULT_10: "true"
      VAULT_TOKEN: "00000000-0000-0000-0000-000000000000"
      VAULT_SCHEME: "http"
      VAULT_HOST: "vault"
      VAULT_PORT: "8200"
      SPRING_PROFILES_ACTIVE: "DEVELOPMENT"
      DEPLOYMENT_ENVIRONMENT: "WORKSHOP"
    depends_on:
      - vault-loader
  vault:
    image: vault:latest
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "00000000-0000-0000-0000-000000000000"
  vault-loader:
    build:
      context: developer-tools/vault-loader
    depends_on:
      - vault
    environment:
      VAULT_ADDR: "http://vault:8200/"
      VAULT_TOKEN: "00000000-0000-0000-0000-000000000000"
