---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
        limits: mem-cpu-limit
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            limits:
              cpu: 100m
              memory: 128Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apache
        limits: no-cpu-limit
    spec:
      containers:
        - name: apache
          image: httpd:latest
          resources:
            limits:
              memory: 128Mi