site_name: Chaos Engine Workshop
site_description: 'A tool for automated Chaos Experimentation'
repo_url: https://github.com/ThalesGroup/chaos-engine
repo_name: chaos-engine @ GitHub
docs_dir: markdown

strict: true

theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'light blue'
    accent: 'light blue'
  font:
    text: Fira Sans Condensed
    code: Fira Code
  feature:
    tabs: true
  favicon: 'https://github.com/ThalesGroup/chaos-engine/raw/master/docs/markdown/images/icon.png'
  logo: 'https://github.com/ThalesGroup/chaos-engine/raw/master/docs/markdown/images/icon.png'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - type: tags
      link: 'https://github.com/ThalesGroup/chaos-engine/issues'

copyright: |
  &copy; 2019 Thales Group<br />
  <!-- version -->