
name: Documentation Builder

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    container:
      image: python:3-alpine
    steps:
      - uses: actions/checkout@v2
        with:
          token: '${{ secrets.PUSH_TOKEN }}'
          persist-credentials: 'true'
      - name: Initialize version variable
        run: echo "::set-env name=VERSION::$(date +%F-%T)"
      - name: Prepare Build Environment
        run: ./scripts/docs/mkdocs_pre_build.sh
      - name: Build Documentation
        run: ./scripts/docs/mkdocs_build.sh
      - name: Publish
        run:  cd docs; mkdocs gh-deploy -v
      - name: Upload Documentation
        uses: actions/upload-artifact@v1
        with:
          name: documentation
          path: "documentation"

