
name: Documentation Builder

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    container:
      image: python:3-alpine
    steps:
      - uses: actions/checkout@v1
      - name: Initialize version variable
        run: echo "::set-env name=VERSION::$(date +%F-%T)"
      - name: Prepare Build Environment
        run: ./scripts/docs/mkdocs_pre_build.sh
      - name: Build Documentation
        run: ./scripts/docs/mkdocs_build.sh
      - name: Publish
        run: cp docs/mkdocs.yml .;cd public; mkdocs gh-deploy -v
      - name: Upload Documentation
        uses: actions/upload-artifact@v1
        with:
          name: documentation
          path: "documentation"

