
name: Documentation Builder

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    container:
      image: python:latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: '${{ secrets.PUSH_TOKEN }}'
          persist-credentials: 'true'
      - name: Initialize Git
        run: git fetch
      - name: Initialize version variable
        run: echo "::set-env name=VERSION::$(date +%F-%T)"
      - name: Prepare Build Environment
        run: bash ./scripts/docs/mkdocs_pre_build.sh
      - name: Build Documentation
        run: bash ./scripts/docs/mkdocs_build.sh
      - name: Publish
        run:  cd docs; mkdocs gh-deploy -v


